name = 'cybernacly'
license = 'MIT'
licenselink = 'https://github.com/xnacly/blog/LICENSE'
description = 'Cyberpunk inspired theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/xnacly/blog/themes/cybernacly'

# If you have a running demo of the theme
demosite = 'xnacly.me'

# Taxonomy terms
tags = ['xnacly', 'cyberpunk']
features = ['minimalist']

# If the theme has a single author
[author]
  name = 'xnacly'
  homepage = 'xnacly.me'
