baseURL = 'https://vrsashly.me/'
title = 'vrsashly - blog'
theme = 'cybernacly'
email = 'contact@vrsashly.me'
canonifyURLs = true
enableRobotsTXT = false

pagination.pagerSize = 4

[markup]

    [markup.highlight]
    style = 'base16-snazzy'
    lineNos = true
    lineNumbersInTable = false

    [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
            [markup.goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$']]
                inline = [['\(', '\)']]


[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[params]
bio = "Back-end Developer and Tech enthusiast"
description = "A blog all around tech, programming and whatever im currently interested in"

    [params.author]
    name = "vrsashly"
    email = "contact@vrsashly.me"

    [params.social]
    github = "https://github.com/vrsashly"
    rss = "https://vrsashly.me/index.xml"
    email = "mailto:contact@vrsashly.me"